### ISSUE TITLE
Cannot open actions menu for multiple tickets

### ISSUE THREAD

**Issue by AlexanderLieret** [jcatrysse/redmine_issue_todo_lists2#9]
Redmine version: 5.1.2.stable
Issue To-do Lists Plugin version: 2.1.8

After selecting multiple tickets, the actions menu cannot be opened. A 500 internal server error is returned.
Opening the actions menu works for single tickets as expected.

Here is the relevant log
```
  Rendered context_menus/issues.html.erb (Duration: 42.5ms | Allocations: 30696)
Completed 500 Internal Server Error in 106ms (ActiveRecord: 19.1ms | Allocations: 54188)

ActionView::Template::Error (Mysql2::Error: Column 'position' in order clause is ambiguous):
    11:           <% icon_class = 'icon icon-add' %>
    12:           <% list_count = 1 %>
    13:           <% li_title = todo_list.project.name + ' - ' + todo_list.title + ': add item' %>
    14:         <% elsif @issue_ids && (@issue_ids - todo_list.issues.ids).empty? %>
    15:           <% icon_class = 'icon icon-del' %>
    16:           <% list_count = -(@issue_ids.count) %>
    17:           <% li_title = todo_list.project.name + ' - ' + todo_list.title + ': unlist all items' %>

plugins/redmine_issue_todo_lists2/app/views/context_menus/issue_todo_lists/_issues_context_menu.html.erb:14
plugins/redmine_issue_todo_lists2/app/views/context_menus/issue_todo_lists/_issues_context_menu.html.erb:5:in `each'
plugins/redmine_issue_todo_lists2/app/views/context_menus/issue_todo_lists/_issues_context_menu.html.erb:5
plugins/redmine_issue_todo_lists2/lib/redmine_issue_todo_lists/hooks/view_issues_context_menu_end_hook.rb:8:in `view_issues_context_menu_end'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `tap'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/context_menus/issues.html.erb:170
app/controllers/context_menus_controller.rb:64:in `issues'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by jcatrysse** [comment]
Thank you, @AlexanderLieret, I also bumped the version.
